[package]
name = "mns-supervisor"
version = "0.1.0"
authors = ["Michael Allwright <allsey87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde-pickle = { version = "0.6" }

tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec", "udp"] }
natnet-decode = { version = "0.1" }
warp = { version = "0.2", features = ["websocket"] }
futures = { version = "0.3" }
static_dir = { version = "0.1" }
thrussh = {path = "crates/thrussh"}
thrussh-keys = "0.17"

bytes = { version = "0.5" }
uuid = { version = "0.8", features = ["serde", "v3", "v4"] }
ipnet = { version = "2.3" }
regex = { version = "1.4" }
lazy_static = { version = "1.4" }
base64 = { version = "0.13" }
itertools = { version = "0.9.0" }

semver = { version = "0.4"}
log = { version = "0.4" }
env_logger = { version = "0.8" }
anyhow = "1.0"
thiserror = { version = "1.0" }




